### ISSUE TITLE
Support for the docker graph drive

### ISSUE THREAD

**Issue by abdulrahmanazab** [RedCoolBeans/docker-volume-beegfs#1]
Hi,

As I understand, this for creating docker volumes on beegfs. What about having the graph drive itself on beegfs, i.e. store the docker images and containers on a beegfs?

**Comment by jasperla** [comment]
Hi,

This plugin is indeed for creating volumes which are stored in the BeeGFS cluster. Doing a graph driver for BeeGFS is not in scope for this particular project, however if there's a need for it, it's certainly worth looking into.

**Comment by jasperla** [comment]
Closing due to lack of input.

**Comment by abdulrahmanazab** [comment]
Sorry @jasperla , my mistake :)
Yes it is definitely needed. At the University of Oslo, we have two clusters, [Abel](http://www.uio.no/english/services/it/research/hpc/abel/) and [Colossus](http://www.uio.no/english/services/it/research/hpc/colossus/). Both are using BeeGFS as the shared file-system. And it is "needed" to have a graph driver for beegfs in order to support docker on the two clusters

**Comment by jasperla** [comment]
Could you please drop me a mail at jasper@redcoolbeans.com so we can see how we can be of help to you and your university?
