### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by Perchework** [RedCoolBeans/docker-volume-beegfs#3]
Hi,

I've got this error when I launch "go build"

`# _/root/dockerfiles/docker-volume-beegfs
./main.go:27: cannot use d (type beegfsDriver) as type volume.Driver in argument to volume.NewHandler:
	beegfsDriver does not implement volume.Driver (missing Capabilities method)
./main.go:28: cannot use "beegfs" (type string) as type int in argument to h.Handler.ServeUnix
zsh: exit 2     go build
`
I'm on ubuntu 16.04 with go version 1.6.2

Thanks for your help

**Comment by reinerj** [comment]
Hi,

we will look at this issue shortly. Thanks for the report

**Comment by deric** [comment]
I'm having same issue with `go version go1.7 linux/amd64` on Debian 8. Is there some requirement on Go version?

**Comment by reinerj** [comment]
hi,

we are just working on a new release which should be published next days. The problem you saw should be fixed.

Thanks

**Comment by reinerj** [comment]
We have a new version which should fix the issue you saw
